function postprocess_hos_jonswap006(out)
%POSTPROCESS_HOS_JONSWAP006 Current joint-modal GL on completed kpHs/2=.06 HOS.
% eta20 is retained as a historical diagnostic; the selected next route is R4.
run='/home/lxy/green-laplace-unidirectional-time-series-runs/hos-jonswap-kphs006-20tp-20260927-v1/medium';
s=jsondecode(fileread(fullfile(run,'settings.json')));
assert(abs(s.kpHs_over_2-.06)<1e-12 && s.expected_samples==1377);
initial=load(fullfile(run,'inputs','initial_fields.mat'),'C','kx','ky','om');
phases=[0,90,180,270];
value=read_probe_file(fullfile(run,'cases','phi000','Results','probes.dat'));
t=value(:,1);raw=zeros(numel(t),5,4);raw(:,:,1)=value(:,2:end);
for phase_index=2:4
    value=read_probe_file(fullfile(run,'cases',sprintf('phi%03d',phases(phase_index)),'Results','probes.dat'));
    assert(isequal(t,value(:,1)));raw(:,:,phase_index)=value(:,2:end);
end
H=zeros(size(raw));for phase_index=1:4,H(:,:,phase_index)=imag(hilbert(raw(:,:,phase_index)));end
first=(raw(:,:,1)-raw(:,:,3)-H(:,:,2)+H(:,:,4))/4;
eta22_ref=(raw(:,:,1)-raw(:,:,2)+raw(:,:,3)-raw(:,:,4))/4;
eta33_ref=(raw(:,:,1)-raw(:,:,3)+H(:,:,2)-H(:,:,4))/4;
eta20_raw=mean(raw,3);N=numel(t);dt=mean(diff(t));
native_frequency=2*pi*[0:floor(N/2),-floor(N/2):-1]'/(N*dt);
omega_p=sqrt(s.g*s.kp*tanh(s.kp*s.h));low_mask=abs(native_frequency)>0&abs(native_frequency)<.5*omega_p;
eta20_ref=real(ifft(fft(eta20_raw).*low_mask));score=t>=s.scoring_window_s(1)&t<=s.scoring_window_s(2);

pred20=zeros(N,5);pred22=pred20;pred33=pred20;rows=zeros(5,23);audits=cell(5,1);
total_clock=tic;
for probe=1:5
    prepare_clock=tic;
    [model,info]=prepare_directional_joint_wavegroup(initial,first(:,probe),t,s,probe,7.5,.999,20);
    prepare_seconds=toc(prepare_clock);audits{probe}=rmfield(info,'input');
    clock=tic;eta22=gl_directional_time_modal_grid( ...
        model.A,model.omega,model.kx,model.ky,s.g,s.h,s.kp,t-t(1), ...
        struct('Nx',256,'Ny',256,'J',8,'Baseband',true));seconds22=toc(clock);
    clock=tic;eta33=gl_directional_time_modal_grid_eta33( ...
        model.A,model.omega,model.kx,model.ky,s.g,s.h,s.kp,t-t(1), ...
        struct('Nx',256,'Ny',256,'J',10,'Baseband',true));seconds33=toc(clock);
    clock=tic;eta20=gl_directional_time_modal_grid_eta20( ...
        model.A,model.omega,model.kx,model.ky,s.g,s.h,t-t(1), ...
        struct('Nx',512,'Ny',512,'J',16));seconds20=toc(clock);
    pred20(:,probe)=real(ifft(fft(eta20).*low_mask));pred22(:,probe)=real(eta22);pred33(:,probe)=real(eta33);
    rows(probe,:)=[probe,info.retained_bins(1),info.retained_bins(end),info.frequency_count, ...
        info.retained_energy_fraction,info.projection_relative, ...
        relative(pred20(:,probe),eta20_ref(:,probe),score), ...
        relative(pred22(:,probe),eta22_ref(:,probe),score), ...
        relative(pred33(:,probe),eta33_ref(:,probe),score), ...
        norm(pred20(score,probe))/norm(eta20_ref(score,probe)), ...
        norm(pred22(score,probe))/norm(eta22_ref(score,probe)), ...
        norm(pred33(score,probe))/norm(eta33_ref(score,probe)), ...
        prepare_seconds,seconds20,seconds22,seconds33, ...
        seconds20+seconds22+seconds33, ...
        max(abs(pred20(score,probe))),max(abs(pred22(score,probe))),max(abs(pred33(score,probe))), ...
        max(abs(eta20_ref(score,probe))),max(abs(eta22_ref(score,probe))),max(abs(eta33_ref(score,probe)))];
end
total_seconds=toc(total_clock);
names={'probe','first_bin','last_bin','frequency_count','retained_first_energy', ...
    'first_projection_relative','eta20_HOS_relative','eta22_HOS_relative','eta33_HOS_relative', ...
    'eta20_norm_ratio','eta22_norm_ratio','eta33_norm_ratio','input_prepare_seconds', ...
    'eta20_seconds','eta22_seconds','eta33_seconds','combined_GL_seconds', ...
    'eta20_max_abs_m','eta22_max_abs_m','eta33_max_abs_m', ...
    'eta20_reference_max_abs_m','eta22_reference_max_abs_m','eta33_reference_max_abs_m'};
metrics=array2table(rows,'VariableNames',names);writetable(metrics,fullfile(out,'metrics.csv'));
timing=struct('MATLAB_threads',maxNumCompThreads,'total_postprocess_seconds',total_seconds, ...
    'median_input_prepare_seconds',median(metrics.input_prepare_seconds), ...
    'median_eta20_seconds',median(metrics.eta20_seconds), ...
    'median_eta22_seconds',median(metrics.eta22_seconds), ...
    'median_eta33_seconds',median(metrics.eta33_seconds), ...
    'median_combined_GL_seconds',median(metrics.combined_GL_seconds), ...
    'eta20_grid',[512,512],'eta20_rank',16,'eta22_grid',[256,256],'eta22_rank',8, ...
    'eta33_grid',[256,256],'eta33_inner_outer_rank',10);
report=struct('source_run',run,'kpHs_over_2',s.kpHs_over_2,'Hs_linear',s.Hs_linear, ...
    'JONSWAP_gamma',s.jonswap_gamma,'seed',s.seed,'samples',N, ...
    'scoring_window_s',s.scoring_window_s,'target_first_energy',.999, ...
    'eta20_scope','diagnostic only; nonzero abs(omega)<0.5 omega_p; strict spatial Q=0 excluded; R4 selected next', ...
    'eta22_scope','positive pure-sum phase sector','eta33_scope','Hilbert third phase sector', ...
    'no_fitting',true,'pair_loops',0,'triple_loops',0,'timing',timing, ...
    'input_audits',{audits},'metrics',table2struct(metrics));
writejson(fullfile(out,'report.json'),report);writejson(fullfile(out,'timing.json'),timing);
save(fullfile(out,'comparison.mat'),'report','metrics','timing','t','first', ...
    'eta20_ref','eta22_ref','eta33_ref','pred20','pred22','pred33','raw','score');
plot_component(t,score,eta20_ref,pred20,'eta20',out);plot_component(t,score,eta22_ref,pred22,'eta22',out);plot_component(t,score,eta33_ref,pred33,'eta33',out);
disp(metrics);disp(timing)
end

function value=read_probe_file(file)
lines=readlines(file);header=find(startsWith(strtrim(lines),'VARIABLES'),1,'last');
value=readmatrix(file,'NumHeaderLines',header);value=value(all(isfinite(value),2),:);
end
function value=relative(candidate,reference,mask),value=norm(candidate(mask)-reference(mask))/norm(reference(mask));end
function plot_component(t,mask,reference,candidate,name,out)
f=figure('Visible','off','Color','w','Position',[100,100,1300,900]);tiledlayout(3,2);
for probe=1:5,nexttile;plot(t,reference(:,probe),'k-',t,candidate(:,probe),'r--');grid on;xlim([t(find(mask,1)),t(find(mask,1,'last'))]);xlabel('Time (s)');ylabel('Elevation (m)');title(sprintf('Probe %d %s',probe,name));if probe==1,legend('HOS phase sector','Joint-modal GL','Location','best');end,end
exportgraphics(f,fullfile(out,name+".png"),'Resolution',150);close(f);
end
function writejson(file,value),fid=fopen(file,'w');assert(fid>=0);fprintf(fid,'%s\n',jsonencode(value));fclose(fid);end
