function records=generate_eta22_rank_data( ...
        reference_source,input_root,output_root,apply_low_output_cutoff)
%GENERATE_ETA22_RANK_DATA Representative J=1,...,12 field ladder.
arguments
    reference_source (1,1) string
    input_root (1,1) string = fullfile('artifacts', ...
        'eta22_playground_rank_inputs')
    output_root (1,1) string = fullfile('artifacts', ...
        'eta22_field_rank_ladder_ce')
    apply_low_output_cutoff (1,1) logical = false
end
if ~isfolder(output_root),mkdir(output_root);end
project_root=string(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(fullfile(project_root,'src','internal'));
addpath(fullfile(project_root,'paper','internal'));
depths=[1 2 4];
definitions={ ...
    struct('id','single_s30','label','One system, 30 deg spreading', ...
        'spread',30,'crossing',0), ...
    struct('id','balanced_spreading_a090_s30', ...
        'label','Two equal systems, 90 deg crossing, 30 deg spreading', ...
        'spread',30,'crossing',90), ...
    struct('id','crossing_a120_s30', ...
        'label','Two equal systems, 120 deg crossing, 30 deg spreading', ...
        'spread',30,'crossing',120)};
case_ids=string(cellfun(@(value)value.id,definitions,'UniformOutput',false));
case_labels=string(cellfun(@(value)value.label,definitions,'UniformOutput',false));
n=numel(depths)*numel(case_ids)*12;
rows=repmat(empty_row(),n,1); row_index=0;
for depth=depths
    depth_tag=strrep(sprintf('%g',depth),'.','p');
    for case_index=1:numel(case_ids)
        case_name="kph"+depth_tag+"_"+case_ids(case_index);
        case_root=fullfile(input_root,case_name);
        state_path=fullfile(case_root,'state_and_reference.mat');
        if ~isfile(state_path)
            if ~isfolder(case_root),mkdir(case_root);end
            configuration=playground_config( ...
                definitions{case_index},depth);
            state=generate_eta22_input(configuration);
            [mf12_reference,mf12_audit]= ...
                mf12_eta22_pure_sum_reference( ...
                state,reference_source);
            save(state_path,'state','mf12_reference','mf12_audit','-v7.3');
        else
            saved=load(state_path,'state','mf12_reference','mf12_audit');
            state=saved.state; mf12_reference=saved.mf12_reference;
        end
        qx=state.depth*state.kx; qy=state.depth*state.ky;
        reference=real(mf12_reference);
        for J=1:12
            row_index=row_index+1;
            [candidate,audit]=green_laplace_eta22( ...
                state.eta11_analytic_spectrum,qx,qy,depth,J,project_root);
            candidate_spectrum=fft2(candidate);
            if apply_low_output_cutoff
                candidate_spectrum(hypot(qx,qy)<=0.6)=0;
            end
            candidate=real(depth*ifft2(candidate_spectrum));
            difference=candidate-reference;
            raw_l2=norm(difference(:))/norm(reference(:));
            raw_linf=max(abs(difference(:)))/max(abs(reference(:)));
            difference_spectrum=fft2(difference);
            low_output=real(ifft2(difference_spectrum.*(hypot(qx,qy)<=0.6)));
            resolved_output=real(ifft2(difference_spectrum.*(hypot(qx,qy)>0.6)));
            low_output_l2=norm(low_output(:))/norm(reference(:));
            resolved_output_l2=norm(resolved_output(:))/norm(reference(:));
            rows(row_index)=struct('kph',depth,'case_id',case_ids(case_index), ...
                'case_label',case_labels(case_index),'J',J, ...
                'raw_relative_l2',raw_l2,'raw_relative_l2_pct',100*raw_l2, ...
                'raw_relative_linf',raw_linf, ...
                'low_output_relative_l2_pct',100*low_output_l2, ...
                'resolved_output_relative_l2_pct',100*resolved_output_l2, ...
                'norm_ratio',norm(candidate(:))/norm(reference(:)), ...
                'fft_ifft_count',audit.fft_ifft_count, ...
                'pointwise_product_count',audit.pointwise_product_count, ...
                'matlab_release',string(version('-release')));
            fprintf('%3d/%3d kph=%g %-24s J=%2d L2=%10.6g%%\n', ...
                row_index,n,depth,case_ids(case_index),J,100*raw_l2);
        end
    end
end
records=struct2table(rows);
writetable(records,fullfile(output_root,'raw_records.csv'));
summary=struct('status','post-freeze-nonselecting-field-rank-ladder', ...
    'ranks',1:12,'depths',depths,'case_ids',case_ids, ...
    'record_count',height(records),'metric','raw same-unit relative L2', ...
    'rescaling_alignment_or_gain',false,'precision','double', ...
    'apply_low_output_cutoff',apply_low_output_cutoff, ...
    'low_output_midpoint_threshold',0.3, ...
    'input_discretization','eta22 playground nested-energy', ...
    'domain_wavelengths',10,'requested_grid_size',256, ...
    'retained_spectral_mass_percent',99, ...
    'reference','MATLAB playground MF12 positive-positive pure-sum eta22 fields', ...
    'matlab_release',version('-release'));
fid=fopen(fullfile(output_root,'summary.json'),'w');
cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(summary,PrettyPrint=true));
delete(cleanup);
end

function config=playground_config(definition,depth)
config=struct('retained_mass_percent',99,'jonswap_gamma',3.3, ...
    'spread_deg',definition.spread, ...
    'crossing_angle_deg',definition.crossing,'peak_kh',depth, ...
    'domain_wavelengths',10,'grid_size',256,'auto_expand_grid',true, ...
    'selection_mode','nested-energy','maximum_components',2500, ...
    'radial_bins',48,'angular_bins',96,'minimum_k_over_kp',0.3, ...
    'maximum_k_over_kp',3.5,'crest_amplitude',0.1, ...
    'time_peak_periods',0,'minimum_output_midpoint_q',0.3);
end

function value=empty_row()
value=struct('kph',NaN,'case_id',"",'case_label',"",'J',NaN, ...
    'raw_relative_l2',NaN,'raw_relative_l2_pct',NaN, ...
    'raw_relative_linf',NaN,'low_output_relative_l2_pct',NaN, ...
    'resolved_output_relative_l2_pct',NaN,'norm_ratio',NaN, ...
    'fft_ifft_count',NaN, ...
    'pointwise_product_count',NaN,'matlab_release',"");
end
