function output_path=figure_eta20_gl_rank( ...
        figure_root,mf12_root,peak_kh)
%FIGURE_ETA20_GL_RANK Matched GL6/GL12/GL16 eta20 comparison.
% Reconstructs the Figure-2 120-degree crossing input at k_p d=1 and compares
% shared GL6/GL12/GL16 with the official finite-component MF12 field.
arguments
    figure_root (1,1) string = string(fullfile('results','paper'))
    mf12_root (1,1) string = string(getenv('MF12_ROOT'))
    peak_kh (1,1) double {mustBePositive,mustBeFinite} = 1
end
if ~isfolder(figure_root),mkdir(figure_root);end
project_root=string(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(fullfile(project_root,'diagnostics','eta20'));
addpath(fullfile(project_root,'diagnostics','eta20','generated'));
addpath(fullfile(project_root,'paper','internal'));
setup_green_laplace("MF12Root",mf12_root);
mf12_source=string(fileparts(which('mf12_spectral_coefficients')));

config=struct('retained_mass_percent',99,'jonswap_gamma',3.3, ...
    'spread_deg',30,'crossing_angle_deg',120,'peak_kh',peak_kh, ...
    'domain_wavelengths',10,'grid_size',256,'auto_expand_grid',true, ...
    'selection_mode','nested-energy','maximum_components',2500, ...
    'radial_bins',48,'angular_bins',96,'minimum_k_over_kp',0.3, ...
    'maximum_k_over_kp',3.5,'crest_amplitude',0.1, ...
    'time_peak_periods',0,'minimum_output_midpoint_q',0.3);
if abs(peak_kh-1)<1e-12
    asset_base="fig_eta20_gl6_gl12_gl16_waveform";
else
    asset_base="fig_eta20_gl6_gl12_gl16_waveform_kph" ...
        +replace(sprintf('%.3g',peak_kh),'.','p');
end
state=generate_eta22_input(config);
eta11_spectrum=state.eta11_spectrum;
kx=state.kx;ky=state.ky;depth=state.depth;
n=size(eta11_spectrum,1);domain_wavelengths=config.domain_wavelengths;
[reference,reference_audit]=mf12_eta20_reference( ...
    eta11_spectrum,kx,ky,depth,mf12_source);
[candidate6_half,audit6]=eta20_green_laplace_shared( ...
    eta11_spectrum,kx,ky,depth,"shared6",project_root);
[candidate12_half,audit12]=eta20_green_laplace_shared( ...
    eta11_spectrum,kx,ky,depth,"shared12",project_root);
[candidate16_half,audit16]=eta20_green_laplace_shared( ...
    eta11_spectrum,kx,ky,depth,"shared16",project_root);
low_output_cutoff=0.3;
[candidate_low_half,audit_low]=eta20_green_laplace_shared( ...
    eta11_spectrum,kx,ky,depth,"endpoint6",project_root);
candidate6=2*candidate6_half;candidate12=2*candidate12_half;
candidate16=2*candidate16_half;
candidate_low=2*candidate_low_half;
output_k_over_k0=hypot(kx,ky);
low_mask=output_k_over_k0>0 & output_k_over_k0<=low_output_cutoff+64*eps;
zero_mask=output_k_over_k0==0;
candidate_band_hat=fft2(candidate6);
candidate_low_hat=fft2(candidate_low);
candidate_band_hat(low_mask)=candidate_low_hat(low_mask);
candidate_band_hat(zero_mask)=0;
candidate_band=real(ifft2(candidate_band_hat));
if ~strcmp(audit6.information_boundary,'eta11-only') ...
        || ~strcmp(audit12.information_boundary,'eta11-only') ...
        || ~strcmp(audit16.information_boundary,'eta11-only') ...
        || ~strcmp(audit_low.information_boundary,'eta11-only')
    error('The post-freeze reference/candidate information boundary failed.');
end
reference_peak=max(abs(reference),[],'all');
reference_norm=norm(reference(:));
difference6=candidate6-reference;difference12=candidate12-reference;
difference16=candidate16-reference;
difference_band=candidate_band-reference;
candidate6_norm=norm(candidate6(:));candidate12_norm=norm(candidate12(:));
candidate16_norm=norm(candidate16(:));
candidate_band_norm=norm(candidate_band(:));
difference6_norm=norm(difference6(:));difference12_norm=norm(difference12(:));
difference16_norm=norm(difference16(:));
difference_band_norm=norm(difference_band(:));
q6=difference6_norm/(reference_norm+candidate6_norm);
q12=difference12_norm/(reference_norm+candidate12_norm);
q16=difference16_norm/(reference_norm+candidate16_norm);
q_band=difference_band_norm/(reference_norm+candidate_band_norm);
method=["GL6";"GL12";"GL16";"GL6 endpoint-band"];ranks=[6;12;16;6];
raw_l2_pct=100*[difference6_norm;difference12_norm;difference16_norm; ...
    difference_band_norm] ...
    /reference_norm;
raw_linf_pct=100*[max(abs(difference6),[],'all'); ...
    max(abs(difference12),[],'all');max(abs(difference16),[],'all'); ...
    max(abs(difference_band),[],'all')] ...
    /reference_peak;
norm_ratios=[candidate6_norm;candidate12_norm;candidate16_norm; ...
    candidate_band_norm]/reference_norm;
q_values=[q6;q12;q16;q_band];
cutoffs=[NaN;NaN;NaN;low_output_cutoff];
low_scales=[NaN;NaN;NaN;audit_low.quadrature_scale];
metrics=table(method,repmat(depth,4,1), ...
    repmat(config.crossing_angle_deg,4,1),repmat(config.spread_deg,4,1), ...
    repmat(n,4,1),repmat(reference_audit.active_positive_parent_count,4,1), ...
    ranks,raw_l2_pct,raw_linf_pct,norm_ratios,q_values,cutoffs,low_scales, ...
    'VariableNames',{'method','peak_kpd','crossing_angle_deg','spread_deg', ...
    'grid_size','selected_component_count','quadrature_rank', ...
    'physical_raw_relative_l2_pct','physical_raw_relative_linf_pct', ...
    'candidate_over_mf12_norm_ratio','surface_similarity_Q', ...
    'low_output_cutoff_k_over_k0','low_quadrature_scale'});
writetable(metrics(1:3,:),fullfile(figure_root,asset_base+"_metrics.csv"));
writetable(metrics(4,:),fullfile(figure_root, ...
    asset_base+"_endpoint_band_diagnostic.csv"));
low_mode_table=low_mode_diagnostics(reference, ...
    {candidate6,candidate12,candidate16,candidate_band}, ...
    ["GL6","GL12","GL16","GL6 endpoint-band"],kx,ky);
writetable(low_mode_table(low_mode_table.method~="GL6 endpoint-band",:), ...
    fullfile(figure_root, ...
    asset_base+"_low_mode_diagnostic.csv"));
writetable(low_mode_table(low_mode_table.method=="GL6 endpoint-band",:), ...
    fullfile(figure_root,asset_base+"_endpoint_band_low_mode_diagnostic.csv"));

carrier_wavenumber=1;
field_scale=config.crest_amplitude^2*carrier_wavenumber;
x=(-n/2:n/2-1)*domain_wavelengths/n;
reference_normalized=fftshift(reference)/field_scale;
candidate6_normalized=fftshift(candidate6)/field_scale;
candidate12_normalized=fftshift(candidate12)/field_scale;
candidate16_normalized=fftshift(candidate16)/field_scale;
candidate_band_normalized=fftshift(candidate_band)/field_scale;
difference6_percent=100*(candidate6_normalized-reference_normalized) ...
    /max(abs(reference_normalized),[],'all');
difference12_percent=100*(candidate12_normalized-reference_normalized) ...
    /max(abs(reference_normalized),[],'all');
difference16_percent=100*(candidate16_normalized-reference_normalized) ...
    /max(abs(reference_normalized),[],'all');
difference_band_percent=100*(candidate_band_normalized-reference_normalized) ...
    /max(abs(reference_normalized),[],'all');
center=n/2+1;
centerlines=table(x(:),reference_normalized(center,:).', ...
    candidate6_normalized(center,:).',candidate12_normalized(center,:).', ...
    candidate16_normalized(center,:).',difference6_percent(center,:).', ...
    difference12_percent(center,:).',difference16_percent(center,:).', ...
    'VariableNames',{'x_over_lambda_p','mf12_eta20_scaled', ...
    'gl6_eta20_scaled','gl12_eta20_scaled','gl16_eta20_scaled', ...
    'gl6_difference_pct_of_mf12_peak','gl12_difference_pct_of_mf12_peak', ...
    'gl16_difference_pct_of_mf12_peak'});
writetable(centerlines,fullfile(figure_root,asset_base+"_centerline.csv"));
endpoint_centerline=table(x(:),candidate_band_normalized(center,:).', ...
    difference_band_percent(center,:).', ...
    'VariableNames',{'x_over_lambda_p','gl6_endpoint_band_eta20_scaled', ...
    'gl6_endpoint_band_difference_pct_of_mf12_peak'});
writetable(endpoint_centerline,fullfile(figure_root, ...
    asset_base+"_endpoint_band_centerline.csv"));

mode_axis=0:n/2;
kx_over_k0=mode_axis/domain_wavelengths;
reference_center_spectrum=abs(fft(reference_normalized(center,:)))/n;
candidate6_center_spectrum=abs(fft(candidate6_normalized(center,:)))/n;
candidate12_center_spectrum=abs(fft(candidate12_normalized(center,:)))/n;
candidate16_center_spectrum=abs(fft(candidate16_normalized(center,:)))/n;
reference_center_spectrum=reference_center_spectrum(1:n/2+1);
candidate6_center_spectrum=candidate6_center_spectrum(1:n/2+1);
candidate12_center_spectrum=candidate12_center_spectrum(1:n/2+1);
candidate16_center_spectrum=candidate16_center_spectrum(1:n/2+1);
spectrum_table=table(kx_over_k0(:), ...
    reference_center_spectrum(:),candidate6_center_spectrum(:), ...
    candidate12_center_spectrum(:),candidate16_center_spectrum(:), ...
    'VariableNames',{'abs_kx_over_k0','mf12_eta20_spectrum_scaled', ...
    'gl6_eta20_spectrum_scaled','gl12_eta20_spectrum_scaled', ...
    'gl16_eta20_spectrum_scaled'});
writetable(spectrum_table,fullfile(figure_root, ...
    asset_base+"_centerline_spectrum.csv"));

display_window=1.5;
field_limit=max(abs([reference_normalized(:);candidate6_normalized(:); ...
    candidate12_normalized(:);candidate16_normalized(:)]));
difference_limit=max(abs([difference6_percent(:);difference12_percent(:); ...
    difference16_percent(:)]));
line_limit=max(abs([reference_normalized(center,:), ...
    candidate6_normalized(center,:),candidate12_normalized(center,:), ...
    candidate16_normalized(center,:)]));
difference_line_limit=max(abs([difference6_percent(center,:), ...
    difference12_percent(center,:),difference16_percent(center,:)]));
blue=[0.0000 0.4470 0.7410];purple=[0.4940 0.1840 0.5560];
green=[0.4660 0.6740 0.1880];orange=[0.8500 0.3250 0.0980];
fig=figure('Color','w','Units','centimeters','Position',[2 2 28 11]);
ax1=axes(fig,'Position',[0.030 0.60 0.180 0.33]);
field_image(ax1,x,reference_normalized,field_limit,display_window, ...
    '(a) MF12 reference',false);
ax2=axes(fig,'Position',[0.255 0.60 0.180 0.33]);
cb2=field_image(ax2,x,candidate6_normalized,field_limit,display_window, ...
    '(b) GL6',true);ylabel(ax2,'');
ax3=axes(fig,'Position',[0.500 0.60 0.180 0.33]);
cb3=field_image(ax3,x,difference6_percent,difference_limit,display_window, ...
    '(c) GL6 difference',true);ylabel(ax3,'');
set(ax1,'Position',[0.030 0.60 0.180 0.33]);
set(ax2,'Position',[0.255 0.60 0.180 0.33]);
set(cb2,'Position',[0.440 0.60 0.009 0.33]);
set(ax3,'Position',[0.500 0.60 0.180 0.33]);
set(cb3,'Position',[0.685 0.60 0.009 0.33]);
set_colorbar_label(fig,[0.455 0.60 0.014 0.33], ...
    '$\eta_{20}/(A^2k_0)$');
set_colorbar_label(fig,[0.704 0.60 0.048 0.33], ...
    '$\mathrm{Difference}\ (\%\ \mathrm{of\ MF12\ peak})$');

ax4=axes(fig,'Position',[0.050 0.08 0.480 0.38]);
h_reference=plot(ax4,x,reference_normalized(center,:),'-', ...
    'Color',[0.12 0.12 0.12],'LineWidth',1.2, ...
    'DisplayName','MF12');hold(ax4,'on');
h_gl6=plot(ax4,x,candidate6_normalized(center,:),'--','Color',blue, ...
    'LineWidth',1.25,'DisplayName','GL6');
h_gl12=plot(ax4,x,candidate12_normalized(center,:),':','Color',purple, ...
    'LineWidth',1.45,'DisplayName','GL12');
h_gl16=plot(ax4,x,candidate16_normalized(center,:),'-.','Color',green, ...
    'LineWidth',1.25,'DisplayName','GL16');
line_style(ax4,display_window*[-1,1],[-line_limit line_limit], ...
    '(e) Centerline comparison','$\eta_{20}/(A^2k_0)$');
legend(ax4,[h_reference h_gl6 h_gl12 h_gl16], ...
    {'MF12','GL6','GL12','GL16'}, ...
    'Location','best','Box','off','Interpreter','latex', ...
    'FontName','CMU Serif','FontSize',8);

ax5=axes(fig,'Position',[0.600 0.08 0.370 0.38]);
plot(ax5,x,difference6_percent(center,:),'-','Color',orange,'LineWidth',1.15, ...
    'DisplayName',sprintf('GL6; full-field Q=%.4f',q6));
hold(ax5,'on');
plot(ax5,x,difference12_percent(center,:),'--','Color',purple,'LineWidth',1.25, ...
    'DisplayName',sprintf('GL12; full-field Q=%.4f',q12));
plot(ax5,x,difference16_percent(center,:),':','Color',green,'LineWidth',1.35, ...
    'DisplayName',sprintf('GL16; full-field Q=%.4f',q16));
line_style(ax5,display_window*[-1,1], ...
    [-difference_line_limit difference_line_limit], ...
    '(f) Centerline error', ...
    '$\mathrm{Difference}\ (\%\ \mathrm{of\ MF12\ peak})$');
legend(ax5,'Location','best','Box','off','Interpreter','none', ...
    'FontName','CMU Serif','FontSize',7);
ax6=axes(fig,'Position',[0.755 0.60 0.185 0.33]);hold(ax6,'on');
spectrum_x_limit=1.0;
visible_spectrum=kx_over_k0<=spectrum_x_limit;
visible_values=[reference_center_spectrum(visible_spectrum).', ...
    candidate6_center_spectrum(visible_spectrum).', ...
    candidate12_center_spectrum(visible_spectrum).', ...
    candidate16_center_spectrum(visible_spectrum).'];
positive_visible_values=visible_values(visible_values>0);
spectrum_floor=0.7*min(positive_visible_values);
spectrum_ceiling=1.15*max(visible_values(:));
patch(ax6,[0 0.3 0.3 0], ...
    [spectrum_floor spectrum_floor spectrum_ceiling spectrum_ceiling], ...
    [0.92 0.92 0.92], ...
    'EdgeColor','none','HandleVisibility','off');
h_spec_ref=semilogy(ax6,kx_over_k0, ...
    max(reference_center_spectrum,spectrum_floor), ...
    '-','Color',[0.12 0.12 0.12],'LineWidth',1.3,'DisplayName','MF12');
h_spec6=semilogy(ax6,kx_over_k0, ...
    max(candidate6_center_spectrum,spectrum_floor), ...
    '--','Color',blue,'LineWidth',1.2,'DisplayName','GL6');
h_spec12=semilogy(ax6,kx_over_k0, ...
    max(candidate12_center_spectrum,spectrum_floor), ...
    ':','Color',purple,'LineWidth',1.4,'DisplayName','GL12');
h_spec16=semilogy(ax6,kx_over_k0, ...
    max(candidate16_center_spectrum,spectrum_floor), ...
    '-.','Color',green,'LineWidth',1.2,'DisplayName','GL16');
grid(ax6,'on');box(ax6,'on');xlim(ax6,[0 spectrum_x_limit]);
ylim(ax6,[spectrum_floor spectrum_ceiling]);
set(ax6,'YScale','log');
set(ax6,'YAxisLocation','right');
xlabel(ax6,'$|k_x|/k_0$');
ylabel(ax6,'$|\widehat{\eta}_{20}|/(A^2k_0)$');
title(ax6,'(d) Centerline spectra','FontWeight','normal');
text(ax6,0.15,1.08*spectrum_floor,'$|k_x|/k_0\leq0.3$', ...
    'HorizontalAlignment','center','VerticalAlignment','bottom', ...
    'Interpreter','latex','FontSize',6.5);
legend(ax6,[h_spec_ref h_spec6 h_spec12 h_spec16], ...
    'Location','northeast','Box','off','Interpreter','latex', ...
    'FontName','CMU Serif','FontSize',6.5);
for ax=[ax1 ax2 ax3 ax4 ax5 ax6],axis_style(ax);end
ax5.YAxis.Exponent=0;ytickformat(ax5,'%.2f');
ax4.YLabel.FontSize=7;ax5.YLabel.FontSize=7;ax6.YLabel.FontSize=7;
cb3.Ruler.Exponent=0;cb3.TickLabels=compose('%.2f',cb3.Ticks);
output_path=fullfile(figure_root,asset_base+".png");
exportgraphics(fig,output_path,'Resolution',600);close(fig);
fprintf(['ETA20_GL6_GL12_GL16_WAVEFORM_COMPLETE kph=%g cross=%g spread=%g ' ...
    'grid=%d components=%d Q6=%.9g Q12=%.9g Q16=%.9g Qband=%.9g %s\n'], ...
    peak_kh,config.crossing_angle_deg, ...
    config.spread_deg,n,state.selected_component_count,q6,q12,q16,q_band, ...
    output_path);
end

function [field,audit]=mf12_eta20_reference( ...
        eta11_spectrum,kx,ky,depth,mf12_root)
source_file=fullfile(mf12_root,'mf12_spectral_coefficients.m');
if ~isfile(source_file),error('Official MF12 source not found: %s',source_file);end
addpath(mf12_root,'-begin');
resolved=string(which('mf12_spectral_coefficients'));
if ~strcmpi(char(resolved),char(source_file))
    error('Unexpected MF12 source resolved: %s',resolved);
end
positive=kx>0;
threshold=1e-13*max(1,max(abs(eta11_spectrum),[],'all'));
parent_indices=find(positive & abs(eta11_spectrum)>threshold);
grid_count=numel(eta11_spectrum);
coefficients_eta=eta11_spectrum(parent_indices)/grid_count;
a=2*real(coefficients_eta);b=2*imag(coefficients_eta);
timer=tic;
coefficients=mf12_spectral_coefficients(2,1.0,depth,a,b, ...
    kx(parent_indices),ky(parent_indices),0.0,0.0);
difference_indices=2:2:numel(coefficients.G_npm);
values=(coefficients.A_npm(difference_indices) ...
    +1i*coefficients.B_npm(difference_indices)) ...
    .*coefficients.G_npm(difference_indices);
delta_kx=kx(1,2)-kx(1,1);delta_ky=ky(2,1)-ky(1,1);
n=size(eta11_spectrum,1);
columns=mod(round(coefficients.kx_npm(difference_indices)/delta_kx),n)+1;
rows=mod(round(coefficients.ky_npm(difference_indices)/delta_ky),n)+1;
one_sided=accumarray([rows(:),columns(:)],values(:),[n n],@sum,complex(0));
one_sided(1,1)=0;
field=real(ifft2(one_sided))*grid_count;
audit=struct('total_seconds',toc(timer), ...
    'active_positive_parent_count',numel(parent_indices), ...
    'strict_zero_mode','set-to-zero-separate-sector', ...
    'external_source',resolved);
end

function cb=field_image(ax,x,field,limit,display_window,title_text,show_colorbar)
imagesc(ax,x,x,field);axis(ax,'xy','equal','tight');
clim(ax,[-limit limit]);colormap(ax,redblue_map(256));
xlim(ax,display_window*[-1,1]);ylim(ax,display_window*[-1,1]);
xlabel(ax,'$x/\lambda_p$');
if show_colorbar
    cb=colorbar(ax);cb.FontName='CMU Serif';cb.TickLabelInterpreter='latex';
else
    cb=gobjects(0);
end
ylabel(ax,'$y/\lambda_p$');title(ax,title_text,'FontWeight','normal');
end

function line_style(ax,x_limits,y_limits,title_text,y_text)
grid(ax,'on');box(ax,'on');xlim(ax,x_limits);ylim(ax,y_limits);
xlabel(ax,'$x/\lambda_p$ at $y/\lambda_p=0$');ylabel(ax,y_text);
title(ax,title_text,'FontWeight','normal');
end

function set_colorbar_label(fig,position,label_text)
label_axes=axes(fig,'Position',position,'Visible','off','HitTest','off');
text(label_axes,0.5,0.5,label_text,'Units','normalized', ...
    'Interpreter','latex','FontName','CMU Serif','FontSize',7, ...
    'Rotation',90,'HorizontalAlignment','center','VerticalAlignment','middle');
end

function axis_style(ax)
set(ax,'FontName','CMU Serif','FontSize',8,'LineWidth',0.75, ...
    'TickDir','out','Layer','top','TickLabelInterpreter','latex');
ax.XLabel.Interpreter='latex';ax.YLabel.Interpreter='latex';
ax.Title.Interpreter='latex';
ax.XLabel.FontName='CMU Serif';ax.YLabel.FontName='CMU Serif';
ax.Title.FontName='CMU Serif';
end

function map=redblue_map(n)
half=floor(n/2);
map=[linspace(0.15,1,half).',linspace(0.35,1,half).',ones(half,1); ...
    ones(n-half,1),linspace(1,0.25,n-half).',linspace(1,0.15,n-half).'];
end

function result=low_mode_diagnostics(reference,candidates,methods,kx,ky)
% Parseval-equivalent full-field Q after excluding low output wave numbers.
thresholds=[0,0.1,0.2,0.3,0.5,1.0];
output_k_over_k0=hypot(kx,ky);n=numel(reference);
reference_hat=fft2(reference);
reference_zero=abs(reference_hat(1,1))/n;
records=struct([]);cursor=0;
for method_index=1:numel(candidates)
    candidate_hat=fft2(candidates{method_index});
    difference_hat=candidate_hat-reference_hat;
    full_q=norm(difference_hat(:)) ...
        /(norm(reference_hat(:))+norm(candidate_hat(:)));
    total_error_energy=sum(abs(difference_hat(:)).^2);
    total_reference_energy=sum(abs(reference_hat(:)).^2);
    for threshold=thresholds
        cursor=cursor+1;
        inside=output_k_over_k0<=threshold+64*eps;
        outside=~inside;
        outside_denominator=norm(reference_hat(outside)) ...
            +norm(candidate_hat(outside));
        if outside_denominator==0
            q_outside=NaN;
        else
            q_outside=norm(difference_hat(outside))/outside_denominator;
        end
        record=struct('method',methods(method_index), ...
            'excluded_k_over_k0_max',threshold, ...
            'excluded_bin_count',nnz(inside), ...
            'reference_zero_mode_amplitude',reference_zero, ...
            'candidate_zero_mode_amplitude',abs(candidate_hat(1,1))/n, ...
            'full_field_Q',full_q,'Q_outside_excluded_region',q_outside, ...
            'error_energy_inside_fraction', ...
                sum(abs(difference_hat(inside)).^2)/total_error_energy, ...
            'reference_energy_inside_fraction', ...
                sum(abs(reference_hat(inside)).^2)/total_reference_energy);
        if cursor==1,records=record;else,records(cursor)=record;end
    end
end
result=struct2table(records);
end
