function generate_matlab_fixtures(matlabRepository,outputDirectory)
%GENERATE_MATLAB_FIXTURES Freeze small FFT--GL cross-language fixtures.
arguments
    matlabRepository (1,1) string
    outputDirectory (1,1) string
end
addpath(matlabRepository);
setup_green_laplace;
if ~isfolder(outputDirectory),mkdir(outputDirectory);end

g=9.81;h=1;Lx=2*pi;Ly=2*pi;Nx=64;Ny=64;
a=[.01,.006];b=[0,-.002];kx=[2,3];ky=[0,1];
coefficients=gl_spectral_coefficients(2,g,h,a,b,kx,ky,0,0, ...
    struct('eta22_rank',6));
[~,~,X,Y,parts]=gl_spectral_surface(coefficients,Lx,Ly,Nx,Ny,0);
spatial=struct( ...
    'gravity',g,'depth',h,'lx',Lx,'ly',Ly,'nx',Nx,'ny',Ny, ...
    'rank',6,'eta1',parts.eta11,'eta22',parts.eta22, ...
    'psi11',parts.psi11,'psi22',parts.psi22,'x',X(1,:),'y',Y(:,1), ...
    'matlab_source_revision','eaca157');
write_json(fullfile(outputDirectory,'directional_spatial_eta22.json'),spatial);

coefficients3=gl_spectral_coefficients(3,g,h,a,b,kx,ky,0,0, ...
    struct('eta22_rank',6));
[~,~,~,~,parts3]=gl_spectral_surface(coefficients3,Lx,Ly,Nx,Ny,0);
spatial3=struct( ...
    'gravity',g,'depth',h,'lx',Lx,'ly',Ly,'nx',Nx,'ny',Ny, ...
    'eta1',parts3.eta11,'eta33',parts3.eta33,'psi33',parts3.psi33, ...
    'matlab_source_revision','eaca157');
write_json(fullfile(outputDirectory,'directional_spatial_order3.json'),spatial3);

% Three-direction field evaluated away from the input time.
aTime=[.009,.005,.0035];bTime=[.001,-.0015,.0008];
kxTime=[2,3,4];kyTime=[0,1,-1];evaluationTime=.7;
inputCoefficients=gl_spectral_coefficients(1,g,h,aTime,bTime, ...
    kxTime,kyTime,0,0);
[~,~,~,~,inputParts]=gl_spectral_surface( ...
    inputCoefficients,Lx,Ly,Nx,Ny,0);
timeCoefficients=gl_spectral_coefficients(3,g,h,aTime,bTime, ...
    kxTime,kyTime,0,0,struct('eta22_rank',8));
[~,~,~,~,timeParts]=gl_spectral_surface( ...
    timeCoefficients,Lx,Ly,Nx,Ny,evaluationTime);
spatialTime=struct( ...
    'gravity',g,'depth',h,'lx',Lx,'ly',Ly,'nx',Nx,'ny',Ny, ...
    'time',evaluationTime,'rank',8,'eta1',inputParts.eta11, ...
    'eta11',timeParts.eta11,'psi11',timeParts.psi11, ...
    'eta22',timeParts.eta22,'psi22',timeParts.psi22, ...
    'eta33',timeParts.eta33,'psi33',timeParts.psi33, ...
    'matlab_source_revision','eaca157');
write_json(fullfile(outputDirectory, ...
    'directional_spatial_nonzero_time.json'),spatialTime);

timeReference=fullfile(matlabRepository,'research', ...
    'unidirectional_time_series','gl_unidirectional_time_series.m');
assert(isfile(timeReference), ...
    'The declared time-reference repository does not contain the MATLAB time executor.');
addpath(fullfile(matlabRepository,'research','unidirectional_time_series'));
N=256;dt=.2;t=(0:N-1)'*dt;
eta1=.01*cos(2*pi*5*(0:N-1)'/N)+.006*cos(2*pi*8*(0:N-1)'/N+.3);
omegaMax=2*pi*8/(N*dt)+1e-12;
options=struct('omega_max',omegaMax,'quadrature_rank',8, ...
    'domain_lengths',[25,50],'spatial_points',[64,128], ...
    'relative_tolerance',1e-12,'order',2);
[result,audit]=gl_unidirectional_time_series(eta1,t,g,h,options);
temporal=struct( ...
    'gravity',g,'depth',h,'rank',8,'time',t,'eta1',eta1, ...
    'eta1_used',result.eta1_used,'eta22',result.eta22, ...
    'domain_lengths',[25,50],'spatial_points',[64,128], ...
    'matlab_input_projection_relative',audit.input_projection_relative, ...
    'matlab_source_revision','ef989ca4fdbd5572f947a4e2f4f7677b59112437');
write_json(fullfile(outputDirectory,'unidirectional_time_eta22.json'),temporal);

options.order=3;
[result3,audit3]=gl_unidirectional_time_series(eta1,t,g,h,options);
temporal3=struct( ...
    'gravity',g,'depth',h,'rank',8,'time',t,'eta1',eta1, ...
    'eta1_used',result3.eta1_used,'eta22',result3.eta22, ...
    'eta33',result3.eta33,'domain_lengths',[25,50], ...
    'spatial_points',[64,128], ...
    'matlab_input_projection_relative',audit3.input_projection_relative, ...
    'matlab_source_revision','ef989ca4fdbd5572f947a4e2f4f7677b59112437');
write_json(fullfile(outputDirectory,'unidirectional_time_order3.json'),temporal3);

F=fft(eta1)/N;bins=(1:8)';omega=2*pi*bins/(N*dt);
A=2*conj(F(bins+1));nu=omega*sqrt(h/g);q=zeros(size(nu));
for index=1:numel(q)
    q(index)=fzero(@(value)value*tanh(value)-nu(index)^2, ...
        [0,max(1,2*nu(index)^2+2)]);
end
eta20Options=struct('Nx',128,'Ny',16,'J',16,'QxLimit',0, ...
    'QyLimit',(2.05*max(q))/(1-2/16));
[eta20,audit20]=gl_directional_time_modal_grid_eta20( ...
    A,omega,q/h,zeros(size(q)),g,h,t,eta20Options);
temporal20=struct( ...
    'gravity',g,'depth',h,'rank',16,'time',t,'eta1',eta1, ...
    'eta20',eta20,'grid',[128,16], ...
    'delta_q_rms_pair',audit20.delta_q_rms_pair, ...
    'matlab_source_revision','ef989ca4fdbd5572f947a4e2f4f7677b59112437');
write_json(fullfile(outputDirectory,'unidirectional_time_eta20.json'),temporal20);

% Fixed-phase multicomponent single-direction record.
Nrandom=384;dtRandom=.25;tRandom=(0:Nrandom-1)'*dtRandom;
randomBins=[3;5;8;11];randomAmplitude=[.008;.006;.004;.003];
randomPhase=[.2;-1.1;.7;2.0];etaRandom=zeros(Nrandom,1);
for index=1:numel(randomBins)
    etaRandom=etaRandom+randomAmplitude(index)*cos( ...
        2*pi*randomBins(index)*(0:Nrandom-1)'/Nrandom+randomPhase(index));
end
omegaRandom=2*pi*randomBins/(Nrandom*dtRandom);
randomOptions=struct('omega_max',omegaRandom(end)+1e-12, ...
    'quadrature_rank',6,'domain_lengths',[25,50], ...
    'spatial_points',[64,128],'relative_tolerance',1e-12,'order',3);
[randomResult,~]=gl_unidirectional_time_series( ...
    etaRandom,tRandom,g,h,randomOptions);
FRandom=fft(etaRandom)/Nrandom;allBins=(1:randomBins(end))';
allOmega=2*pi*allBins/(Nrandom*dtRandom);allA=2*conj(FRandom(allBins+1));
allNu=allOmega*sqrt(h/g);allQ=zeros(size(allNu));
for index=1:numel(allQ)
    allQ(index)=fzero(@(value)value*tanh(value)-allNu(index)^2, ...
        [0,max(1,2*allNu(index)^2+2)]);
end
randomEta20Options=struct('Nx',128,'Ny',16,'J',12,'QxLimit',0, ...
    'QyLimit',(2.05*max(allQ))/(1-2/16));
[randomEta20,~]=gl_directional_time_modal_grid_eta20( ...
    allA,allOmega,allQ/h,zeros(size(allQ)),g,h,tRandom,randomEta20Options);
temporalRandom=struct( ...
    'gravity',g,'depth',h,'rank',6,'eta20_rank',12, ...
    'time',tRandom,'eta1',etaRandom,'eta20',randomEta20, ...
    'eta22',randomResult.eta22,'eta33',randomResult.eta33, ...
    'omega_max',omegaRandom(end)+1e-12,'domain_lengths',[25,50], ...
    'spatial_points',[64,128],'eta20_grid',[128,16], ...
    'matlab_source_revision','ef989ca4fdbd5572f947a4e2f4f7677b59112437');
write_json(fullfile(outputDirectory, ...
    'unidirectional_time_fixed_phase.json'),temporalRandom);
end

function write_json(path,value)
file=fopen(path,'w');assert(file>=0);
cleanup=onCleanup(@()fclose(file));
fprintf(file,'%s\n',jsonencode(value));
end
