import pathlib,subprocess,os,hashlib,json,shutil
r=pathlib.Path('/home/lxy/green-laplace-unidirectional-time-series-runs/hos-mpi-check-20260926-v1');b=pathlib.Path('/home/lxy/green-laplace-unidirectional-time-series/artifacts/hos-ocean-v2.1.0');dep=r/'deps/usr';lib=dep/'lib/x86_64-linux-gnu'
p=dep/'share/openmpi/mpifort.openmpi-wrapper-data.txt';shutil.copy2(p,p.with_suffix('.original'));s=p.read_text();assert 'libdir=${libdir}/fortran/gfortran' in s;s=s.replace('libdir=${libdir}/fortran/gfortran','libdir='+str(lib/'openmpi/lib'));p.write_text(s)
env=os.environ.copy();env['OPAL_PREFIX']=str(dep);env['PMIX_MCA_mca_base_component_path']=str(lib/'pmix2/lib/pmix');env['LD_LIBRARY_PATH']=':'.join(map(str,[lib,b/'deps/usr/lib/x86_64-linux-gnu',b/'deps/usr/lib/x86_64-linux-gnu/lapack',b/'deps/usr/lib/x86_64-linux-gnu/blas']));env['OMPI_FC']=str(b/'precision-v1/gfortran')
for k in ['OMP_NUM_THREADS','OPENBLAS_NUM_THREADS','MKL_NUM_THREADS']:env[k]='1'
(r/'environment.json').write_text(json.dumps({k:env[k] for k in ['OPAL_PREFIX','PMIX_MCA_mca_base_component_path','LD_LIBRARY_PATH','OMPI_FC','OMP_NUM_THREADS','OPENBLAS_NUM_THREADS','MKL_NUM_THREADS']},indent=2))
src=r/'source';subprocess.run(['git','clone','--no-hardlinks',str(b/'source'),str(src)],check=True);patch=pathlib.Path('/home/lxy/green-laplace-unidirectional-time-series-runs/hos-gl-timeseries-20260926-v1/hos-io.patch');subprocess.run(['git','-C',str(src),'apply',str(patch)],check=True)
commands=[([str(dep/'bin/mpifort.openmpi'),'--showme'],'wrapper.log'),(['cmake','-S',str(src),'-B',str(r/'build'),'-DCMAKE_Fortran_COMPILER='+env['OMPI_FC'],'-DMPI_Fortran_COMPILER='+str(dep/'bin/mpifort.openmpi'),'-DMPIEXEC_EXECUTABLE='+str(dep/'bin/mpirun.openmpi'),'-DUSE_MPI=ON','-DUSE_HDF5=OFF','-DBUILD_TESTING=OFF','-DCMAKE_Fortran_FLAGS=-I'+str(dep/'include'),'-DFFTW3_MPI_LIBRARY='+str(lib/'libfftw3_mpi.so'),'-DBLAS_LIBRARIES='+str(b/'deps/usr/lib/x86_64-linux-gnu/blas/libblas.so.3'),'-DLAPACK_LIBRARIES='+str(b/'deps/usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3')+';'+str(b/'deps/usr/lib/x86_64-linux-gnu/blas/libblas.so.3')],'configure.log'),(['cmake','--build',str(r/'build'),'--target','HOS-Ocean','-j','2'],'build.log')]
for args,name in commands:
    with (r/name).open('w') as f:p=subprocess.run(args,env=env,stdout=f,stderr=subprocess.STDOUT)
    assert p.returncode==0,(r/name).read_text()[-5000:]
    print(name+' OK',flush=True)
(r/'build-provenance.json').write_text(json.dumps({'binary_sha256':hashlib.sha256((r/'build/sources/HOS-Ocean').read_bytes()).hexdigest(),'upstream_commit':subprocess.check_output(['git','-C',str(src),'rev-parse','HEAD'],text=True).strip(),'io_patch_sha256':hashlib.sha256(patch.read_bytes()).hexdigest(),'packages':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in (r/'debs').glob('*.deb')}},indent=2))