function [eta44_plus,audit,components,state44] = ...
    finite_depth_directional_green_laplace_eta44_three_kernels( ...
    eta11_spectrum,qx,qy,peak_depth_qp,project_root,options)
%FINITE_DEPTH_DIRECTIONAL_GREEN_LAPLACE_ETA44_THREE_KERNELS No-Stokes eta44 graph.
% Evaluates the user-directed GL core without any order-four Stokes repair.
% Required flat-potential lower states are generated internally by the frozen
% nested Green--Laplace graph and are not exposed as public candidate outputs.
% No tuple/reference field, MF12 result, or external higher-order state is
% accepted.  The historical function name is retained for path compatibility.

arguments
    eta11_spectrum (:,:) {mustBeNumeric}
    qx (:,:) double
    qy (:,:) double
    peak_depth_qp (1,1) double {mustBePositive}
    project_root (1,1) string = string( ...
        fileparts(fileparts(fileparts(mfilename('fullpath')))))
    options.quadrature_rank (1,1) double {mustBeInteger,mustBePositive} = 4
end
if ~ismember(options.quadrature_rank,[4,6,8,10,12])
    error('Unsupported no-Stokes order-four Green--Laplace rank.');
end
if ~isequal(size(eta11_spectrum),size(qx),size(qy))
    error('Spectrum, qx, and qy must have identical sizes.');
end
forcing_freeze = load_and_verify_forcing_freeze(project_root);
q = hypot(qx,qy);
nu = sqrt(q.*tanh(q));
A = q.*tanh(q);
sqrt_A = sqrt(A);
threshold = 1e-13*max(1,max(abs(eta11_spectrum(:))));
support = abs(eta11_spectrum)>threshold;
if ~any(support,'all') || any(qx(support)<=0) || any(q(support)<=0)
    error('Strict-forward eta11 support with every parent q>0 is required.');
end
assert_quartic_support_is_alias_safe(support);
quartic_support = real(ifft2(fft2(double(support)).^4))>0.5;
surface_requested = nargout>=4;
minimum_parent_nu=min(nu(support));
maximum_quartic_a=max(sqrt_A(quartic_support));
outer_balance_shift=0.5*(minimum_parent_nu+maximum_quartic_a/4);

[nodes,weights] = gauss_laguerre_rule(options.quadrature_rank);
lambda4 = 4*sqrt(peak_depth_qp*tanh(peak_depth_qp)) ...
    -sqrt(4*peak_depth_qp*tanh(4*peak_depth_qp));
if ~isfinite(lambda4) || lambda4<=0
    error('Frozen order-four Green--Laplace tail scale is invalid.');
end

eta_core_spectrum = complex(zeros(size(q)));
psi_core_spectrum = complex(zeros(size(q)));
fft_count = 0;
product_count = 0;
lower_fft_count = 0;
lower_product_count = 0;
partition_product_count = 0;
for outer_index = 1:options.quadrature_rank
    node = nodes(outer_index);
    time = node/lambda4;
    damped_spectrum = eta11_spectrum.*exp( ...
        -time*(nu-outer_balance_shift));
    [~,lower_audit,~,third,state12] = ...
        finite_depth_directional_nested_green_laplace_eta33( ...
        damped_spectrum,qx,qy,peak_depth_qp,project_root, ...
        include_eta_time=surface_requested, ...
        quadrature_rank=options.quadrature_rank);
    if lower_audit.stokes_correction_used ...
            || lower_audit.inner_quadrature_rank~=options.quadrature_rank ...
            || lower_audit.outer_quadrature_rank~=options.quadrature_rank
        error('The nested lower-state graph violates the requested rank or no-Stokes policy.');
    end
    first = state12.first;
    pair = state12.pair;
    [forcing_k,forcing_d,forcing_products] = ...
        order4_forcing(first,pair,third);
    forcing_k_spectrum = fft2(forcing_k);
    forcing_d_spectrum = fft2(forcing_d);
    forcing_k_spectrum(~quartic_support) = 0;
    forcing_d_spectrum(~quartic_support) = 0;
    forcing_k_spectrum=suppress_fft_roundoff( ...
        forcing_k_spectrum,quartic_support);
    forcing_d_spectrum=suppress_fft_roundoff( ...
        forcing_d_spectrum,quartic_support);
    sinh_over_a = time*ones(size(q));
    nonzero = sqrt_A>0;
    sinh_over_a(nonzero) = ...
        sinh(sqrt_A(nonzero)*time)./sqrt_A(nonzero);
    coefficient = weights(outer_index)*exp(node)/lambda4 ...
        *exp(-4*outer_balance_shift*time);
    eta_core_spectrum = eta_core_spectrum+coefficient*( ...
        A.*sinh_over_a.*forcing_d_spectrum ...
        -1i*cosh(sqrt_A*time).*forcing_k_spectrum);
    if surface_requested
        [contact,contact_t,contact_products] = ...
            order4_surface_contact(first,pair,third);
        contact_spectrum = fft2(contact);
        contact_t_spectrum = fft2(contact_t);
        contact_spectrum(~quartic_support) = 0;
        contact_t_spectrum(~quartic_support) = 0;
        contact_spectrum=suppress_fft_roundoff( ...
            contact_spectrum,quartic_support);
        contact_t_spectrum=suppress_fft_roundoff( ...
            contact_t_spectrum,quartic_support);
        forcing_k_surface = forcing_k_spectrum+A.*contact_spectrum;
        forcing_d_surface = forcing_d_spectrum-contact_t_spectrum;
        psi_core_spectrum = psi_core_spectrum+coefficient*( ...
            -1i*cosh(sqrt_A*time).*forcing_d_surface ...
            -sinh_over_a.*forcing_k_surface);
        fft_count = fft_count+2;
        product_count = product_count+contact_products;
    end
    lower_fft_count = lower_fft_count+lower_audit.fft_ifft_count;
    lower_product_count = lower_product_count+ ...
        lower_audit.pointwise_product_count;
    fft_count = fft_count+lower_audit.fft_ifft_count+2;
    product_count = product_count+ ...
        lower_audit.pointwise_product_count+forcing_products;
    partition_product_count = partition_product_count+forcing_products;
end
eta_core_spectrum(~quartic_support) = 0;

eta44_plus = ifft2(eta_core_spectrum);
fft_count = fft_count+1;
if any(~isfinite(eta44_plus),'all')
    error('The no-Stokes GL-core eta44 field is not finite.');
end

audit = struct( ...
    'status','user-directed-no-stokes-core', ...
    'candidate_id','gl-core-no-stokes', ...
    'output_variable','eta44_plus', ...
    'information_boundary','eta11-only', ...
    'external_lower_state_used',false, ...
    'oracle_or_mf12_used',false, ...
    'learned_coefficient_count',0, ...
    'quadrature_rank',options.quadrature_rank, ...
    'nested_rank_tuple',repmat(options.quadrature_rank,1,3), ...
    'quadrature_rank_meaning', ...
        'same radial node count in order-two, order-three, and order-four responses', ...
    'outer_scale',lambda4, ...
    'outer_balance_shift',outer_balance_shift, ...
    'numerical_stability_policy', ...
        'balanced separated exponentials plus FFT backward-error suppression', ...
    'forcing_partitions',{{'1+1+1+1','2+1+1','2+2','3+1'}}, ...
    'lower_state_fft_ifft_count',lower_fft_count, ...
    'lower_state_pointwise_product_count',lower_product_count, ...
    'order4_forcing_product_count',partition_product_count, ...
    'order4_stokes_correction_used',false, ...
    'all_nested_stokes_corrections_used',false, ...
    'fft_ifft_count',fft_count, ...
    'pointwise_product_count',product_count, ...
    'pair_loops',0, ...
    'triple_loops',0, ...
    'quadruple_loops',0, ...
    'cost_class','fixed-constant N log N', ...
    'forcing_freeze_generator',string(forcing_freeze.generator));
components = struct( ...
    'core_spectrum',eta_core_spectrum, ...
    'order4_stokes_correction_used',false);
state44 = struct();
if surface_requested
    psi_core_spectrum(~quartic_support) = 0;
    psi44_plus = ifft2(psi_core_spectrum);
    fft_count = fft_count+1;
    if any(~isfinite(psi44_plus),'all')
        error('The direct surface Psi44 field is not finite.');
    end
    state44 = struct( ...
        'Psi44',psi44_plus, ...
        'Psi44_spectrum',psi_core_spectrum, ...
        'order4_stokes_correction_used',false, ...
        'fft_ifft_count',fft_count, ...
        'pointwise_product_count',product_count);
end
end

function [forcing_k,forcing_d,products] = order4_forcing(first,pair,third)
% These four named blocks are certified exactly against the Wolfram Euler
% forcing by finite_depth_directional_order4_forcing_graph.json.
k31 = first.phix.*third.etax+first.phiy.*third.etay ...
    +third.phix.*first.etax+third.phiy.*first.etay ...
    -first.eta.*third.phizz-third.eta.*first.phizz;
d31 = first.eta.*third.phizt+third.eta.*first.phitz ...
    +first.phix.*third.phix+first.phiy.*third.phiy ...
    +first.phiz.*third.phiz;

k22 = pair.phix.*pair.etax+pair.phiy.*pair.etay ...
    -pair.eta.*pair.phizz;
d22 = pair.eta.*pair.phitz ...
    +0.5*(pair.phix.^2+pair.phiy.^2+pair.phiz.^2);

k211 = first.eta.*(first.phixz.*pair.etax ...
    +first.phiyz.*pair.etay) ...
    +(first.eta.*pair.phixz+pair.eta.*first.phixz).*first.etax ...
    +(first.eta.*pair.phiyz+pair.eta.*first.phiyz).*first.etay ...
    -0.5*first.eta.^2.*pair.phizzz ...
    -first.eta.*pair.eta.*first.phizzz;
d211 = 0.5*first.eta.^2.*pair.phizz_t ...
    +first.eta.*pair.eta.*first.phitzz ...
    +first.phix.*(first.eta.*pair.phixz+pair.eta.*first.phixz) ...
    +first.phiy.*(first.eta.*pair.phiyz+pair.eta.*first.phiyz) ...
    +first.phiz.*(first.eta.*pair.phizz+pair.eta.*first.phizz) ...
    +pair.phix.*(first.eta.*first.phixz) ...
    +pair.phiy.*(first.eta.*first.phiyz) ...
    +pair.phiz.*(first.eta.*first.phizz);

k1111 = 0.5*first.eta.^2.*( ...
    first.phixzz.*first.etax+first.phiyzz.*first.etay) ...
    -first.eta.^3.*first.phizzzz/6;
d1111 = first.eta.^3.*first.phizzz_t/6 ...
    +0.5*first.eta.^2.*(first.phix.*first.phixzz ...
        +first.phiy.*first.phiyzz+first.phiz.*first.phizzz) ...
    +0.5*first.eta.^2.*(first.phixz.^2 ...
        +first.phiyz.^2+first.phizz.^2);

forcing_k = k1111/8+k211/4+k22/2+k31/2;
forcing_d = d1111/8+d211/4+d22/2+d31/2;
products = 64;
end

function [contact,contact_t,products] = ...
    order4_surface_contact(first,pair,third)
contact = 0.5*first.eta.*third.phiz ...
    +0.5*pair.eta.*pair.phiz ...
    +0.5*third.eta.*first.phiz ...
    +0.125*first.eta.^2.*pair.phizz ...
    +0.25*first.eta.*pair.eta.*first.phizz ...
    +(1/48)*first.eta.^3.*first.phizzz;
contact_t = 0.5*(first.eta_t.*third.phiz ...
        +first.eta.*third.phizt) ...
    +0.5*(pair.eta_t.*pair.phiz+pair.eta.*pair.phiz_t) ...
    +0.5*(third.eta_t.*first.phiz+third.eta.*first.phiz_t) ...
    +0.125*(2*first.eta.*first.eta_t.*pair.phizz ...
        +first.eta.^2.*pair.phizz_t) ...
    +0.25*(first.eta_t.*pair.eta.*first.phizz ...
        +first.eta.*pair.eta_t.*first.phizz ...
        +first.eta.*pair.eta.*first.phizz_t) ...
    +(1/48)*(3*first.eta.^2.*first.eta_t.*first.phizzz ...
        +first.eta.^3.*first.phizzz_t);
products = 32;
end

function forcing = load_and_verify_forcing_freeze(project_root)
forcing_path = fullfile(project_root,'symbolic','generated', ...
    'finite_depth_directional_order4_forcing_graph.json');
if ~isfile(forcing_path)
    error('Frozen Wolfram eta44 forcing interface is missing.');
end
forcing = jsondecode(fileread(forcing_path));
if ~forcing.overall_exact_gate_pass || forcing.oracle_or_mf12_used ...
        || forcing.target_eta44_kernel_used
    error('Order-four forcing freeze crossed its information boundary.');
end
end

function [nodes,weights] = gauss_laguerre_rule(rank)
indices=1:rank;
jacobi=diag(2*indices-1)+diag(1:rank-1,1)+diag(1:rank-1,-1);
[vectors,values]=eig(jacobi,'vector');
[nodes,order]=sort(real(values));
vectors=vectors(:,order);
weights=real(vectors(1,:)).^2;
nodes=nodes(:).';weights=weights(:).';
end

function spectrum = suppress_fft_roundoff(spectrum,support)
active_values=abs(spectrum(support));
if isempty(active_values),return,end
scale=max(active_values);
if scale==0,return,end
relative_floor=16*eps*max(1,log2(numel(spectrum)));
spectrum(support & abs(spectrum)<relative_floor*scale)=0;
end

function assert_quartic_support_is_alias_safe(support)
[ny,nx] = size(support);
mode_x = [0:(ceil(nx/2)-1),-floor(nx/2):-1];
mode_y = [0:(ceil(ny/2)-1),-floor(ny/2):-1];
[column,row] = meshgrid(mode_x,mode_y);
if max(4*abs(column(support)))>=nx/2 ...
        || max(4*abs(row(support)))>=ny/2
    error('Quartic output support reaches a Nyquist boundary.');
end
end
