function comparison = gl_mf12_order2_comparison(coeffs,Lx,Ly,Nx,Ny,t)
%GL_MF12_ORDER2_COMPARISON Compare pure-sum eta22 and surface psi22.
%   MF12 is an optional external dependency configured by
%   setup_green_laplace("MF12Root",path). Metrics are raw and unaligned.

source = which('mf12_spectral_coefficients');
if isempty(source)
    error('green_laplace:MF12NotConfigured', ...
        'Configure MF12Root with setup_green_laplace first.');
end
if coeffs.order<2
    error('green_laplace:ComparisonOrder', ...
        'The order-two comparison requires coeffs.order>=2.');
end

[~,~,X,Y,gl_parts,gl_audit] = ...
    gl_spectral_surface(coeffs,Lx,Ly,Nx,Ny,t);
mf = mf12_spectral_coefficients(2,coeffs.g,coeffs.h, ...
    coeffs.a,coeffs.b,coeffs.kx,coeffs.ky,coeffs.Ux,coeffs.Uy, ...
    0,struct('enable_subharmonic',false));

delta_kx = 2*pi/Lx;
delta_ky = 2*pi/Ly;
eta_spectrum = complex(zeros(Ny,Nx));
psi_spectrum = complex(zeros(Ny,Nx));
scale = Nx*Ny;
for parent = 1:numel(coeffs.a)
    phase = exp(-1i*2*mf.omega(parent)*t);
    amplitude = complex(mf.A_2(parent),mf.B_2(parent));
    add_value(2*coeffs.kx(parent),2*coeffs.ky(parent), ...
        scale*amplitude*mf.G_2(parent)*phase, ...
        scale*1i*amplitude*mf.mu_2(parent)*phase);
end

pair = 0;
for first = 1:numel(coeffs.a)
    for second = (first+1):numel(coeffs.a)
        pair = pair+1;
        plus = 2*pair-1;
        phase = exp(-1i*mf.omega_npm(plus)*t);
        amplitude = complex(mf.A_npm(plus),mf.B_npm(plus));
        add_value(coeffs.kx(first)+coeffs.kx(second), ...
            coeffs.ky(first)+coeffs.ky(second), ...
            scale*amplitude*mf.G_npm(plus)*phase, ...
            scale*1i*amplitude*mf.mu_npm(plus)*phase);
    end
end

mf_eta22_plus = ifft2(eta_spectrum);
mf_psi22_plus = ifft2(psi_spectrum);
gl_eta22 = gl_parts.eta22;
gl_psi22 = gl_parts.psi22;
mf_eta22 = real(mf_eta22_plus);
mf_psi22 = real(mf_psi22_plus);

comparison = struct( ...
    'X',X,'Y',Y, ...
    'gl_eta22',gl_eta22,'mf12_eta22',mf_eta22, ...
    'gl_psi22',gl_psi22,'mf12_psi22',mf_psi22, ...
    'eta22_metrics',raw_metrics(gl_eta22,mf_eta22), ...
    'psi22_metrics',raw_metrics(gl_psi22,mf_psi22), ...
    'gl_audit',gl_audit, ...
    'mf12_source',source, ...
    'mf12_parent_count',numel(coeffs.a), ...
    'sector','positive pure-sum order two', ...
    'rescaling_alignment_or_gain',false);

    function add_value(kx_value,ky_value,eta_value,psi_value)
        mode_x = round(kx_value/delta_kx);
        mode_y = round(ky_value/delta_ky);
        if abs(kx_value-mode_x*delta_kx)>coeffs.options.grid_tolerance ...
                || abs(ky_value-mode_y*delta_ky)> ...
                coeffs.options.grid_tolerance
            error('green_laplace:OffGridMF12', ...
                'An MF12 pure-sum output is off the requested FFT grid.');
        end
        if abs(mode_x)>=Nx/2 || abs(mode_y)>=Ny/2
            error('green_laplace:MF12Nyquist', ...
                'An MF12 pure-sum output reaches a Nyquist boundary.');
        end
        column = mod(mode_x,Nx)+1;
        row = mod(mode_y,Ny)+1;
        eta_spectrum(row,column) = eta_spectrum(row,column)+eta_value;
        psi_spectrum(row,column) = psi_spectrum(row,column)+psi_value;
    end
end

function metrics = raw_metrics(candidate,reference)
difference = candidate-reference;
reference_norm = norm(reference(:));
reference_peak = max(abs(reference),[],'all');
metrics = struct( ...
    'raw_relative_l2',norm(difference(:))/max(reference_norm,realmin), ...
    'raw_relative_linf',max(abs(difference),[],'all') ...
        /max(reference_peak,realmin), ...
    'norm_ratio',norm(candidate(:))/max(reference_norm,realmin), ...
    'candidate_max',max(candidate,[],'all'), ...
    'candidate_min',min(candidate,[],'all'), ...
    'reference_max',max(reference,[],'all'), ...
    'reference_min',min(reference,[],'all'));
end
