function table_out = gl_supported_sectors()
%GL_SUPPORTED_SECTORS Public total-field outputs and applicability table.
table_out = table( ...
    [1;2;2;3;3], ...
    ["eta11, psi11";"eta22";"psi22";"eta33";"psi33"], ...
    ["linear";"pure-sum";"pure-sum";"pure-sum";"pure-sum"], ...
    ["k>0";"kh>0";"kh>=0.3";"kh>0.5";"kh>0.5"], ...
    ["released";"released";"released";"bounded";"bounded"], ...
    'VariableNames',{'Order','Components','Sector','ParentDomain','Status'});
end
