function table_out = gl_supported_diagnostics()
%GL_SUPPORTED_DIAGNOSTICS Non-production diagnostics shipped with v0.2.
table_out=table( ...
    ["eta20";"eta20";"eta20";"eta20";"eta20";"eta20"], ...
    ["GL6";"GL12";"GL16";"R2";"R4";"R6"], ...
    ["Green--Laplace";"Green--Laplace";"Green--Laplace"; ...
     "Neumann";"Neumann";"Neumann"], ...
    ["fixed FFT";"fixed FFT";"fixed FFT"; ...
     "ordered pair";"ordered pair";"ordered pair"], ...
    [true;true;true;false;false;false], ...
    ["rank diagnostic";"rank diagnostic";"rank diagnostic"; ...
     "accuracy diagnostic";"accuracy diagnostic";"accuracy diagnostic"], ...
    'VariableNames',{'Component','Method','Family','EvaluationGraph', ...
    'FixedFFTValidated','Status'});
end
